/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import IntermediateSinglePlayerRB.RealClient;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gmyrianthous
 */
public class AIBiddingGUI extends javax.swing.JFrame {
    private int currentBid;
    private String currentSuit;
    private ArrayList<String> bids;
    private RealClient client;
    private String bid = "";
    private boolean hasSubmitted = false;
    
    /**
     * Creates new form AIBiddingGUI
     */
    public AIBiddingGUI(RealClient client, int currentBid, String currentSuit, ArrayList<String> bids) {
        initComponents();
        this.currentBid = currentBid;
        this.currentSuit = currentSuit;
        this.bids = bids;
        this.client = client;
        
        // Draw bidding history.
        drawCurrentBiddings();
        
        // Set biddings restrictions
        setBiddingRestrictions();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
        
    } // AIBiddingGUI

    private void drawCurrentBiddings() {
        if (this.bids.size() != 0){
            for (int i = 0; i < this.bids.size(); i++){
                // bids.get(i) form: 'playerID_bid_suit'
                String bidding = this.bids.get(i);
                String[] splitBidding = bidding.split("_");
                if (splitBidding.length == 3){
                    int playerID = Integer.parseInt(splitBidding[0]);
                    int bid = Integer.parseInt(splitBidding[1]);
                    String suit = splitBidding[2];
                    String playerName;
                    if (playerID == 0)
                        playerName = client.getName();
                    else 
                        playerName = "Bot " + playerID;

                    this.biddingsHistoryJTextArea.append(playerName + " declared " 
                                                         + bid + " of " + suit + "\n");
                } else {
                    int playerID = Integer.parseInt(splitBidding[0]);
                    String playerName;
                    if (playerID == 0)
                        playerName = client.getName();
                    else 
                        playerName = "Bot " + playerID;
                    this.biddingsHistoryJTextArea.append(playerName + " declared pass.\n");
                } // else
            } // for
        } // if
    } // drawCurrentBiddings()
    
    private void setBiddingRestrictions() {
        for (int i = this.currentBid + 1; i < 39; i++)
            this.biddingsJComboBox.addItem(new Integer(i));
    } // setBiddingRestrrictions()
    
    public String getBid(){
        return this.bid;
    } // getBid()
    
    private void setBid(String b) {
        this.bid = b;
    } // setBid
    
    public boolean getHasSubmitted(){
        return this.hasSubmitted;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passJButton = new javax.swing.JButton();
        bidJButton = new javax.swing.JButton();
        biddingsJComboBox = new javax.swing.JComboBox();
        heartsJRadioButton = new javax.swing.JRadioButton();
        diamondsJRadioButton = new javax.swing.JRadioButton();
        clubsJRadioButton = new javax.swing.JRadioButton();
        spadesJRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        biddingsHistoryJTextArea = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(71, 113, 165));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bidding Round");

        passJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        passJButton.setText("Pass");
        passJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passJButtonActionPerformed(evt);
            }
        });

        bidJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bidJButton.setText("Bid");
        bidJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidJButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(heartsJRadioButton);
        heartsJRadioButton.setText("Hearts");

        buttonGroup1.add(diamondsJRadioButton);
        diamondsJRadioButton.setText("Diamonds");
        diamondsJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diamondsJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(clubsJRadioButton);
        clubsJRadioButton.setText("Clubs");

        buttonGroup1.add(spadesJRadioButton);
        spadesJRadioButton.setText("Spades");

        biddingsHistoryJTextArea.setEditable(false);
        biddingsHistoryJTextArea.setBackground(new java.awt.Color(204, 204, 204));
        biddingsHistoryJTextArea.setColumns(20);
        biddingsHistoryJTextArea.setLineWrap(true);
        biddingsHistoryJTextArea.setRows(5);
        biddingsHistoryJTextArea.setAutoscrolls(false);
        biddingsHistoryJTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Bidding History"));
        jScrollPane1.setViewportView(biddingsHistoryJTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(heartsJRadioButton)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biddingsJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clubsJRadioButton)
                            .addComponent(diamondsJRadioButton)
                            .addComponent(spadesJRadioButton)
                            .addComponent(bidJButton))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(heartsJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(diamondsJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clubsJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(biddingsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(spadesJRadioButton)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passJButton)
                    .addComponent(bidJButton))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diamondsJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diamondsJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diamondsJRadioButtonActionPerformed

    private void passJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passJButtonActionPerformed
        // TODO add your handling code here:
        setBid("0_Pass");
        hasSubmitted = true;
        dispose();
    }//GEN-LAST:event_passJButtonActionPerformed

    private void bidJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidJButtonActionPerformed
        // TODO add your handling code here:
        String selectedSuit = "";
        int selectedBid = 0;
        
        if (this.heartsJRadioButton == null && this.diamondsJRadioButton == null
            && this.clubsJRadioButton == null && this.spadesJRadioButton == null){
            JOptionPane.showMessageDialog(null, "Please select suit", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (this.biddingsJComboBox == null){
            JOptionPane.showMessageDialog(null, "Please select a bid", "Error", JOptionPane.ERROR_MESSAGE);
        } else { // everything is OK.
            selectedBid = (int) this.biddingsJComboBox.getSelectedItem();
            if (this.heartsJRadioButton.isSelected())
            selectedSuit = "Hearts";
            else if (this.diamondsJRadioButton.isSelected())
            selectedSuit = "Diamonds";
            else if (this.clubsJRadioButton.isSelected())
            selectedSuit = "Clubs";
            else
            selectedSuit = "Spades";
        } // else
        
        String finalBid = 0 + "_" + selectedBid + "_" + selectedSuit;
        setBid(finalBid);
        hasSubmitted = true;
        dispose();
    }//GEN-LAST:event_bidJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bidJButton;
    private javax.swing.JTextArea biddingsHistoryJTextArea;
    private javax.swing.JComboBox biddingsJComboBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clubsJRadioButton;
    private javax.swing.JRadioButton diamondsJRadioButton;
    private javax.swing.JRadioButton heartsJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton passJButton;
    private javax.swing.JRadioButton spadesJRadioButton;
    // End of variables declaration//GEN-END:variables
}
