/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.LevelSelection;
import GUI.HowToPlayGUI;
import GUI.AboutGUI;
import IntermediateSinglePlayerRB.AIClient;
import IntermediateSinglePlayerRB.AIGame;
import IntermediateSinglePlayerRB.RealClient;
import Multiplayer.ChatClient;
import Multiplayer.Client;
import PointsCalculator.PointsCalculator;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

/**
 *
 * @author gmyrianthous
 */
public class MainSignedIn extends javax.swing.JFrame {
    /**
     * Creates new form GUI
     */
    public static JFrame gui;
    private static Client client;
    private static ChatClient chatClient;
    
    public MainSignedIn() {
        gui = new JFrame();
        //gui.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        initComponents();
        this.singlePlayerJButton.setBackground(Color.BLACK);
        this.setResizable(false);
        gui.setLocationRelativeTo(null);
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
    } // GUI
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        singlePlayerJButton = new javax.swing.JButton();
        multiplayerJButton = new javax.swing.JButton();
        exitJButton = new javax.swing.JButton();
        howToPlayJButton = new javax.swing.JButton();
        aboutJButton = new javax.swing.JButton();
        pointsCalculatorJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("e-Pilotta");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pilotta.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 590, 270);

        singlePlayerJButton.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        singlePlayerJButton.setText("Single Player");
        singlePlayerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerJButtonActionPerformed(evt);
            }
        });

        multiplayerJButton.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        multiplayerJButton.setText("Multiplayer");
        multiplayerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplayerJButtonActionPerformed(evt);
            }
        });

        exitJButton.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        exitJButton.setText("Exit");
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        howToPlayJButton.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        howToPlayJButton.setText("How to play");
        howToPlayJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayJButtonActionPerformed(evt);
            }
        });

        aboutJButton.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        aboutJButton.setText("About");
        aboutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJButtonActionPerformed(evt);
            }
        });

        pointsCalculatorJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        pointsCalculatorJButton.setText("Points Calculator");
        pointsCalculatorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsCalculatorJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(multiplayerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(singlePlayerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointsCalculatorJButton)
                    .addComponent(howToPlayJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aboutJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(exitJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singlePlayerJButton)
                    .addComponent(howToPlayJButton)
                    .addComponent(aboutJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitJButton)
                    .addComponent(multiplayerJButton)
                    .addComponent(pointsCalculatorJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void aboutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJButtonActionPerformed
        // TODO add your handling code here:
                /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutGUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_aboutJButtonActionPerformed

    private void multiplayerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplayerJButtonActionPerformed
        // TODO add your handling code here:
        client = new Client();
        Thread clientThread = new Thread(client);
        clientThread.start();
        
        //this.multiplayerJButton.setEnabled(false);
    }//GEN-LAST:event_multiplayerJButtonActionPerformed

    private void singlePlayerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerJButtonActionPerformed
        // TODO add your handling code here:
        LevelSelection lvl = new LevelSelection();
        lvl.setVisible(true);
    }//GEN-LAST:event_singlePlayerJButtonActionPerformed

    private void howToPlayJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayJButtonActionPerformed
        // TODO add your handling code here:
        new HowToPlayGUI().setVisible(true);
    }//GEN-LAST:event_howToPlayJButtonActionPerformed

    private void pointsCalculatorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsCalculatorJButtonActionPerformed
        // TODO add your handling code here:
        new PointsCalculator().setVisible(true);
    }//GEN-LAST:event_pointsCalculatorJButtonActionPerformed

    public static Client getClient(){
        return client;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutJButton;
    private javax.swing.JButton exitJButton;
    private javax.swing.JButton howToPlayJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplayerJButton;
    private javax.swing.JButton pointsCalculatorJButton;
    private javax.swing.JButton singlePlayerJButton;
    // End of variables declaration//GEN-END:variables
}
