/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.AICarpetGUI;
import java.awt.Color;

/**
 *
 * @author gmyrianthous
 */
public class SinglePlayerUserPreferencesGUI extends javax.swing.JFrame {

    private AICarpetGUI carpet;
    /**
     * Creates new form SinglePlayerUserPreferencesGUI
     */
    public SinglePlayerUserPreferencesGUI(AICarpetGUI c) {
        this.carpet = c;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    } // SinglePlayerUserPreferencesGUI

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        blueDeckJRadioButton = new javax.swing.JRadioButton();
        redDeckJRadioButton = new javax.swing.JRadioButton();
        cancelJButton = new javax.swing.JButton();
        defaultsJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        greenCarpetJRadioButton = new javax.swing.JRadioButton();
        blueCarpetJRadioButton = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        greyCarpetJRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("User Preferences");

        jLabel2.setText("Deck colour");

        buttonGroup1.add(blueDeckJRadioButton);
        blueDeckJRadioButton.setText("Blue (Default)");
        blueDeckJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueDeckJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(redDeckJRadioButton);
        redDeckJRadioButton.setText("Red");

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        defaultsJButton.setText("Set to defaults");
        defaultsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultsJButtonActionPerformed(evt);
            }
        });

        saveJButton.setText("Save & Exit");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Carpet colour");

        buttonGroup2.add(greenCarpetJRadioButton);
        greenCarpetJRadioButton.setText("Green (Default)");

        buttonGroup2.add(blueCarpetJRadioButton);
        blueCarpetJRadioButton.setText("Blue");

        buttonGroup2.add(greyCarpetJRadioButton);
        greyCarpetJRadioButton.setText("Grey");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultsJButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(greenCarpetJRadioButton)
                                .addGap(32, 32, 32)
                                .addComponent(blueCarpetJRadioButton)
                                .addGap(67, 67, 67)
                                .addComponent(greyCarpetJRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(blueDeckJRadioButton)
                                .addGap(41, 41, 41)
                                .addComponent(redDeckJRadioButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueDeckJRadioButton)
                    .addComponent(redDeckJRadioButton))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenCarpetJRadioButton)
                    .addComponent(blueCarpetJRadioButton)
                    .addComponent(greyCarpetJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(saveJButton)
                    .addComponent(defaultsJButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blueDeckJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueDeckJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueDeckJRadioButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if (this.blueDeckJRadioButton.isSelected() && !this.redDeckJRadioButton.isSelected()) {
            this.carpet.setBlueDeck();
        } else if (!this.blueDeckJRadioButton.isSelected() && this.redDeckJRadioButton.isSelected()) {
            this.carpet.setRedDeck();
        } // else if
        
        if (this.greenCarpetJRadioButton.isSelected() && !this.blueCarpetJRadioButton.isSelected()) {
            this.carpet.setGreenCarpet();
        } else if (!this.greenCarpetJRadioButton.isSelected() && this.blueCarpetJRadioButton.isSelected()) {
            this.carpet.setBlueCarpet();
        } else if (this.greyCarpetJRadioButton.isSelected()){
            this.carpet.setGreyCarpet();
            
        } // else if
        
        dispose();
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void defaultsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultsJButtonActionPerformed
        // TODO add your handling code here:
        this.blueDeckJRadioButton.setSelected(true);
        this.greenCarpetJRadioButton.setSelected(true);
        this.carpet.setBlueDeck();
        this.carpet.setGreenCarpet();
        
    }//GEN-LAST:event_defaultsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueCarpetJRadioButton;
    private javax.swing.JRadioButton blueDeckJRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JButton defaultsJButton;
    private javax.swing.JRadioButton greenCarpetJRadioButton;
    private javax.swing.JRadioButton greyCarpetJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton redDeckJRadioButton;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
}
